name: flutter_practical
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 
  flutter_screenutil: 
  dio:
  get_storage: 
  carousel_slider: ^5.0.0
  firebase_core:
  flutter_svg:
  googleapis: 
  googleapis_auth:
  http: 
  firebase_messaging: 
  flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: quicksand
      fonts:
        - asset: assets/fonts/static/Quicksand-Regular.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
